Repository Loss-Leader-Project/Backend, pull requests merged in 2022-03, with the labels that each got.

#9 Add : 이메일 설정 추가
  build.gradle
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/dto/EMail.java
  src/main/java/lossleaderproject/back/user/dto/EmailVerification.java
  src/main/java/lossleaderproject/back/user/dto/EmailVerificationNumber.java
  src/main/java/lossleaderproject/back/user/dto/SendEmail.java
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
  src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
  src/main/java/lossleaderproject/back/user/service/MailService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
  src/main/resources/application.yml
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#13 Add : 비밀번호 찾기 API
  .gitignore
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/dto/UserFindPassword.java
  src/main/java/lossleaderproject/back/user/dto/UserLoginIdFindRequest.java
  src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
  src/main/java/lossleaderproject/back/user/mail/dto/EMail.java
  src/main/java/lossleaderproject/back/user/mail/dto/EmailVerification.java
  src/main/java/lossleaderproject/back/user/mail/dto/EmailVerificationNumber.java
  src/main/java/lossleaderproject/back/user/mail/dto/SendEmail.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/repository/UserRepository.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
  src/main/resources/application.yml
Labels: Status : Self Refactoring 완료, Status : peer 리뷰요청, Status: Merge 승인 요청

#14 Add : 아이디 중복 검사 API
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
Labels: Status: Merge 완료, Status: Merge 승인 요청

#17 Add: minio 연결 세팅
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/controller/StoreDetailController.java
  src/main/java/lossleaderproject/back/store/dto/StoreHashTagRequest.java
  src/main/java/lossleaderproject/back/store/dto/StoreMenuRequest.java
  src/main/java/lossleaderproject/back/store/repository/StoreFoodImageRepository.java
  src/main/java/lossleaderproject/back/store/service/StoreFoodImageService.java
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#16 Add : 마이페이지 - 리뷰 API
  src/main/java/lossleaderproject/back/order/entity/Orders.java
  src/main/java/lossleaderproject/back/order/repository/OrderRepository.java
  src/main/java/lossleaderproject/back/order/repository/StoreOrderRepository.java
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
  src/main/java/lossleaderproject/back/review/dto/ReviewRequest.java
  src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
  src/main/java/lossleaderproject/back/review/entity/Review.java
  src/main/java/lossleaderproject/back/review/entity/ReviewImage.java
  src/main/java/lossleaderproject/back/review/repository/ReviewImageRepository.java
  src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
  src/main/java/lossleaderproject/back/review/service/ReviewImageService.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/dto/StoreMenuRequest.java
  src/main/java/lossleaderproject/back/store/entitiy/StoreDetail.java
  src/main/java/lossleaderproject/back/store/entitiy/StoreFoodImage.java
  src/main/java/lossleaderproject/back/store/entitiy/StoreHashTag.java
  src/main/java/lossleaderproject/back/store/entitiy/StoreMenu.java
  src/main/java/lossleaderproject/back/store/repository/StoreFoodImageRepository.java
  src/main/java/lossleaderproject/back/store/repository/StoreHashTagRepository.java
  src/main/java/lossleaderproject/back/store/repository/StoreMenuRepository.java
  src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
  src/main/java/lossleaderproject/back/store/service/StoreDetailService.java
  src/main/java/lossleaderproject/back/store/service/StoreFoodImageService.java
  src/main/java/lossleaderproject/back/store/service/StoreHashTagService.java
  src/main/java/lossleaderproject/back/store/service/StoreMenuService.java
  src/main/java/lossleaderproject/back/store/service/StoreService.java
  src/main/resources/application.yml
Labels: Status : 기능 구현중

#19 Fix:리스트 페이지 리스팅
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
  src/main/java/lossleaderproject/back/review/dto/ReviewRequest.java
  src/main/java/lossleaderproject/back/review/service/ReviewImageService.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/controller/StoreDetailController.java
  src/main/java/lossleaderproject/back/store/dto/StoreListingResponse.java
  src/main/java/lossleaderproject/back/store/dto/StoreMenuRequest.java
  src/main/java/lossleaderproject/back/store/dto/StoreRequest.java
  src/main/java/lossleaderproject/back/store/dto/StoreResponse.java
  src/main/java/lossleaderproject/back/store/entitiy/Store.java
  src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
  src/main/java/lossleaderproject/back/store/service/StoreService.java
Labels: Status: Merge 승인 요청

#20 Add: 리스트 페이지 리뷰 리스팅
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
  src/main/java/lossleaderproject/back/review/dto/ReviewImageResponse.java
  src/main/java/lossleaderproject/back/review/dto/ReviewRequest.java
  src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
  src/main/java/lossleaderproject/back/review/entity/Review.java
  src/main/java/lossleaderproject/back/review/entity/ReviewImage.java
  src/main/java/lossleaderproject/back/review/repository/ReviewImageRepository.java
  src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
  src/main/java/lossleaderproject/back/review/service/ReviewImageService.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/entitiy/Store.java
  src/main/java/lossleaderproject/back/store/service/StoreService.java
Labels: Status: Merge 승인 요청

#21 Add 마이 페이지 리뷰 리스팅 API
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
  src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#12 Add : 일반 로그인 API
  .gitignore
  build.gradle
  src/main/java/lossleaderproject/back/BackApplication.java
  src/main/java/lossleaderproject/back/security/CorsConfig.java
  src/main/java/lossleaderproject/back/security/SecurityConfig.java
  src/main/java/lossleaderproject/back/security/auth/PrincipalDetails.java
  src/main/java/lossleaderproject/back/security/auth/PrincipalDetailsService.java
  src/main/java/lossleaderproject/back/security/exception/JwtExceptionFilter.java
  src/main/java/lossleaderproject/back/security/jwt/AccessToken.java
  src/main/java/lossleaderproject/back/security/jwt/JwtAuthenticationFilter.java
  src/main/java/lossleaderproject/back/security/jwt/JwtAuthorizationFilter.java
  src/main/java/lossleaderproject/back/security/jwt/Token.java
  src/main/java/lossleaderproject/back/store/dto/StoreDetailRequest.java
  src/main/java/lossleaderproject/back/user/controller/LoginController.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/dto/Login.java
  src/main/java/lossleaderproject/back/user/dto/NewUserResponse.java
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
  src/main/java/lossleaderproject/back/user/entity/User.java
  src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
  src/main/java/lossleaderproject/back/user/service/LoginService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/lossleaderproject/back/user/service/UserServiceTest.java
Labels: Status : peer 리뷰요청, Status: Merge 완료, Status: Merge 승인 요청

#23 Add : 네이버 간편 로그인 설정
  build.gradle
  src/main/java/lossleaderproject/back/security/SecurityConfig.java
  src/main/java/lossleaderproject/back/security/auth/PrincipalDetails.java
  src/main/java/lossleaderproject/back/security/jwt/AccessToken.java
  src/main/java/lossleaderproject/back/security/jwt/JwtAuthenticationFilter.java
  src/main/java/lossleaderproject/back/security/oauth/provider/TokenProvider.java
  src/main/java/lossleaderproject/back/user/controller/LoginController.java
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
  src/main/java/lossleaderproject/back/user/entity/User.java
  src/main/java/lossleaderproject/back/user/service/LoginService.java
  src/main/resources/application.yml
Labels: Status: Merge 승인 요청

#24 Swagger 구현
  build.gradle
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/order/repository/StoreOrderRepository.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/controller/StoreDetailController.java
  src/main/java/lossleaderproject/back/swagger/SwaggerConfig.java
  src/main/java/lossleaderproject/back/user/controller/LoginController.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
  src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
  src/main/resources/application.yml
Labels: Status: Merge 승인 요청

#25 Fix: 메인페이지 res 변경
  Dockerfile
  jenkins/Dockerfile
  jenkins/docker_install.sh
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/dto/StoreDetailResponse.java
  src/main/java/lossleaderproject/back/store/dto/StoreResponse.java
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#28 Add: 이미지 사이즈 리사이즈 4:3
  build.gradle
  src/main/java/lossleaderproject/back/minio/ImageUtils.java
  src/main/java/lossleaderproject/back/minio/MinioService.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/service/StoreFoodImageService.java
  src/main/resources/application.yml
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#27 Improve : 주문에 대한 리팩토링
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/order/dto/OrderRequest.java
  src/main/java/lossleaderproject/back/order/entity/Orders.java
  src/main/java/lossleaderproject/back/order/repository/StoreOrderRepository.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/security/SecurityConfig.java
  src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/entity/User.java
  src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/repository/UserRepository.java
  src/main/java/lossleaderproject/back/user/service/LoginService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
  src/main/resources/application.yml
Labels: Status : peer 리뷰요청, Status: Self Refactoring 진행중

#30 Fix: 피드백 사항 반영
  build.gradle
  src/main/java/lossleaderproject/back/minio/MinioService.java
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
  src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/security/CorsConfig.java
  src/main/java/lossleaderproject/back/security/oauth/provider/TokenProvider.java
  src/main/java/lossleaderproject/back/store/controller/StoreController.java
  src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
  src/main/java/lossleaderproject/back/store/service/StoreService.java
  src/main/java/lossleaderproject/back/user/entity/User.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
  src/main/resources-dev/application.yml
  src/main/resources-prod/application.yml
Labels: Status: Merge 완료

#29 Fix : 회원,주문에 대한 리팩토링
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/order/dto/ProductOrder.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/security/CorsConfig.java
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
  src/main/java/lossleaderproject/back/user/dto/UserResponse.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
Labels: Status: Merge 완료

#31 Fix: 피드백 반영
  src/main/java/lossleaderproject/back/order/dto/OrderHistory.java
  src/main/java/lossleaderproject/back/order/entity/Orders.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
  src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
  src/main/java/lossleaderproject/back/review/entity/Review.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/dto/UserResponse.java
  src/main/java/lossleaderproject/back/user/service/LoginService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#32 이메일 인증, 비밀번호 찾기
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/order/dto/OrderRequest.java
  src/main/java/lossleaderproject/back/order/dto/OrderResponse.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/security/CorsConfig.java
  src/main/java/lossleaderproject/back/security/oauth/provider/TokenProvider.java
  src/main/java/lossleaderproject/back/user/controller/LoginController.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/service/LoginService.java
  src/main/resources-prod/application.yml
Labels: Status : Self Refactoring 완료, Status: Merge 완료

#37 Fix : 로그아웃, 정규식, 비밀번호 암호화, 회원가입 사용자 구별 리팩토링
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/security/SecurityConfig.java
  src/main/java/lossleaderproject/back/user/controller/LoginController.java
  src/main/java/lossleaderproject/back/user/controller/UserController.java
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/repository/UserRepository.java
  src/main/java/lossleaderproject/back/user/service/LoginService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
Labels: Status: Merge 승인 요청

#38 Fix : 리뷰 의존성 수정, 일반 회원 구별, 주문자 일치 여부
  build.gradle
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/security/SecurityConfig.java
  src/main/java/lossleaderproject/back/user/controller/LoginController.java
  src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/repository/UserRepository.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
Labels: Status : Self Refactoring 완료, Status : peer 리뷰요청
