Repository Loss-Leader-Project/Backend, pull requests merged in 2022-04, with the labels that each got.

#39 Add: review exception 추가
  src/main/java/lossleaderproject/back/error/reviewException/ReviewControllerAdvice.java
  src/main/java/lossleaderproject/back/error/reviewException/ReviewCustomException.java
  src/main/java/lossleaderproject/back/error/reviewException/ReviewErrorCode.java
  src/main/java/lossleaderproject/back/error/reviewException/ReviewErrorResponse.java
  src/main/java/lossleaderproject/back/error/userException/UserControllerAdvice.java
  src/main/java/lossleaderproject/back/error/userException/UserCustomException.java
  src/main/java/lossleaderproject/back/error/userException/UserErrorCode.java
  src/main/java/lossleaderproject/back/error/userException/UserErrorResponse.java
  src/main/java/lossleaderproject/back/order/controller/OrderController.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/review/controller/ReviewController.java
  src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
  src/main/java/lossleaderproject/back/review/service/ReviewService.java
  src/main/java/lossleaderproject/back/security/exception/JwtExceptionFilter.java
  src/main/java/lossleaderproject/back/security/jwt/JwtAuthorizationFilter.java
  src/main/java/lossleaderproject/back/user/mail/service/MailService.java
  src/main/java/lossleaderproject/back/user/service/UserService.java
Labels: Status : peer 리뷰요청, Status: Merge 승인 요청

#40 Fix : 주문시 회원정보 확인,쿠폰 주문시 쿠폰 개수 차감
  .gitignore
  gradlew
  src/main/java/lossleaderproject/back/error/userException/UserErrorCode.java
  src/main/java/lossleaderproject/back/order/service/OrderService.java
  src/main/java/lossleaderproject/back/store/entitiy/Store.java
  src/main/resources-dev/application.yml
  src/main/resources-prod/application.yml
Labels: Status: Self Refactoring 진행중

#46 Add: git action yml file
  .github/workflows/pr-test.yml
Labels: Status : peer 리뷰요청

#48 Fix : 회원가입시 주소 null 허용
  src/main/java/lossleaderproject/back/user/dto/UserRequest.java
Labels: Status : peer 리뷰요청
